### ISSUE TITLE
[BUG] GPS missing from Exif in Android 10

### ISSUE THREAD

**Issue by hwasoocho** [CaiJingLong/flutter_photo_manager#148]
**Describe the bug**
Android 10 introduced new privacy update, disallowing access to original images without permission. [Here is a stackoverflow post on solving this issue](https://stackoverflow.com/questions/57980935/exifinterface-gps-not-read-on-android-q-10).

**To Reproduce**
1. Get Exif from `AssetEntity.fullData`
2. Exif returns GPS Latitude and Longitude of [0/0, 0/0, 0/0], which is invalid.

**Expected behavior**
Should be able to request user for permission and use original file path if granted the permission.

**Flutter version**
Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)

**Smartphone (please complete the following information):**
 - Device: Galaxy S10e
 - OS: Android 10

**Comment by CaiJingLong** [comment]
In androidQ, this part requires local permissions to obtain.
I need to design a new api to implement it to distinguish whether positioning permissions are needed.

**Comment by hwasoocho** [comment]
Hi thank you for your response. Is there any plan for when this can be implemented?

**Comment by CaiJingLong** [comment]
If nothing else, I will complete this issue in the next week.

But I have the following questions:
I want to try to keep the semantics of the api on both ends of iOS / Android unified.
Because iOS has a new policy when reviewing the app in 2019, if I invoke the positioning-related permissions, I need to fill in the description of the positioning in the project's plist. As long as it is in the code, it must be added, not the actual call. .
So I have been hesitant to solve this problem, not that there are technical difficulties in implementing this problem.

**Comment by hwasoocho** [comment]
Ah I see. I would be perfectly happy with different API's that would be deprecated by new unified one in the future. But anyways, I thank you for this project. It's made my side project with Flutter a possibility.

**Comment by CaiJingLong** [comment]
I implement it in #152 .
Please wait next version, I will upload new version this week.

**Comment by CaiJingLong** [comment]
I implement it in #152 .
Please wait next version, I will upload new version this week.

**Comment by CaiJingLong** [comment]
New version will wait few days.
