### ISSUE TITLE
[BUG] Bad pictures quality on Samsung?

### ISSUE THREAD

**Issue by rignaneseleo** [CaiJingLong/flutter_photo_manager#237]
Recently I noticed that the quality of a picture showed set using the propriety `size` of `AssetEntity` is really low on Samsung devices.

I tested it using values 100 and 1000 and on Samsung devices the quality is always low (like a really compressed picture) while on other devices the quality is really bad at 100 but turns good at 1000. 

How can that be? 

I'm using  `photo version: 0.4.8` and `photo_manager: 0.4.8`.

**Comment by CaiJingLong** [comment]
hi, I fixed it in photo_manager 0.5.0. I will merge some change and roll back to 0.5.x in next few days.

**Comment by rignaneseleo** [comment]
Thanks for your work!

**Comment by CaiJingLong** [comment]
@rignaneseleo 
Thank you for your suggestion. I checked the plugin you wrote. 

I and your specific approach will be different. Not only trigger the system broadcast. 

https://github.com/CaiJingLong/flutter_photo_manager/blob/8ab010347ba1772c2191411e223d0dae83398270/android/src/main/kotlin/top/kikt/imagescanner/core/utils/DBUtils.kt#L575-L640

Like my saveVideo or saveImage code, I will insert many fields as possible to MediaStore so that I can get more valid fields when using photo_manager to get assets.

**Comment by CaiJingLong** [comment]
By the way, if you are just using photo_manager, this change has been on the pub for a week.

The photo library has been updated in recent days.

**Comment by rignaneseleo** [comment]
Is the bug related to Android 10 or just Samsung? The v0.5.0 doesn't seems to fix the bug on my Samsung with Android 10.

**Comment by CaiJingLong** [comment]
Because my device is also an android10 device, I also tried it including the simulator, and found no similar problems.

So, I will try to write an example.
If necessary, I need you to use the example I provided to output some information to me to help me determine the problem.

**Comment by CaiJingLong** [comment]
Can you try running your code on other Android 10 devices? Like an emulator? Try to see if you have the same problem.

If the same problem occurs with many different devices, then I would assume that the problem is in the code of the library, but instead may be specific to the brand.

**Comment by rignaneseleo** [comment]
On my Android 10 emulator both 0.4.8 and 0.5.0 work well.

**Comment by CaiJingLong** [comment]
Can you try using 0.5.1-dev.3 to test Samsung's API availability?
