### ISSUE TITLE
Png images are not being fetched.

### ISSUE THREAD

**Issue by ShizaS** [CaiJingLong/flutter_photo_manager#303]
I've followed the documentation to implement this feature in my app. But the problem is I'm having some png images on my phone but when I fetch images using this package those png images don't show up/or are not being fetched. I can't figure out what the issue is. Any help will be appreciated

 - Device: Mi9T/Iphone8+
 - OS: android10 /iOS13

**Comment by TheLastGimbus** [comment]
Me too. This is a big issue. @CaiJingLong, please take a look at this :pray:

My app doesn't even see my `Screenshots` folder, because it contains only png's

By the way: `RequestType` class is _really_ weird. Some weird bits moving and comparations instead of... just being a small enum. Also, stuff like `all` and `common` - the `type` field shoud just take a list, and they wouldn't be needed :+1:

**Comment by AlexV525** [comment]
Is this still reproducible on the latest version?

Also, we should file another issue for purpose/advice/feature requests.

**Comment by TheLastGimbus** [comment]
@AlexV525 Sorry for not responding :grimacing: I'm back to working with this library and yes, this is still very much an issue :confused:

**Comment by AlexV525** [comment]
We don't have any mechasim to filter extensions yet. Please try the `ignoreSize` flag in the `SizeConstraint`.

**Comment by TheLastGimbus** [comment]
Is there some extension whitelist that this plugin supports? Or does it pass everything that android media store gives you?

**Comment by AlexV525** [comment]
> Or does it pass everything that android media store gives you?

Exactly.

**Comment by TheLastGimbus** [comment]
Okayyy, `ignoreSize` works :100:
