### ISSUE TITLE
[Feature] Get latitude, longitude synchronously

### ISSUE THREAD

**Issue by hwasoocho** [CaiJingLong/flutter_photo_manager#310]
**Is your feature request related to a problem? Please describe.**
Currently `latlngAsync()` runs on the main thread and takes quite some time to complete. It is difficult to achieve 60 fps while requesting latitude, longitude from multiple asset entities.

**Describe the solution you'd like**
Latitude and longitude to be readily available in AssetEntity. Currently there already are properties `_latitude` and `_longitude` but they return 0.0.

**Describe alternatives you've considered**
Using flutter isolate with `latlngAsync()`, but this is blocked by https://github.com/flutter/flutter/issues/13937

**Comment by hwasoocho** [comment]
Hi, is it possible to get latitude and longitude of an asset entity synchronously on Android? If not I would like to contribute using background job and caching.

**Comment by CaiJingLong** [comment]
Latitude and longitude vary greatly in Android.
1. In androidQ, from Exif, this field is not stored in the database, so it cannot be obtained synchronously
2. The following androidQ comes from the database of MediaStore, but it may be NULL or 0.

For below androidQ or iOS, it can be synchronized, otherwise it won't work.
