### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mohsenzamani22** [CaiJingLong/flutter_photo_manager#364]
There is one very very big problem about this library
When user has multiple videos with high quality ? because library caches all files in app data path , it will cause to full the device storage and makes app closes. 
The cache is idea is nice but you do not use if for videos

**Comment by CaiJingLong** [comment]
For iOS, if you need to use `dart:io` file api to manipulate video files, you must cache them, because iOS provides only the abstract concept of asset, not the provided file entity.

---

You should delete the cache after using the video, such as uploading to the server or other situations.
If you want to preview locally (play with video_player), you can consider using getMediaUrl(), this method will provide an api without adding additional cache.

**Comment by CaiJingLong** [comment]
Then, this is not a bug.

**Comment by CaiJingLong** [comment]
I use #373 to add a method to clear file cache.
It needs to be called by the developer.  

https://github.com/CaiJingLong/flutter_photo_manager#clear-file-cache
And 0.6.0-dev.4
