### ISSUE TITLE
[BUG]Paging loading and sorting problem

### ISSUE THREAD

**Issue by wang-zeqi** [CaiJingLong/flutter_photo_manager#381]
When the page is loaded, sort by createTime, the order of the displayed pictures will be problematic, some pictures are inserted in the middle position instead of all loaded below。

**Comment by lyio** [comment]
I also had weird results when sorting by createTime. 

When looking into the actual values that were returned from the native side I noticed that in a lot of cases the createTime was actually 0.

So that might be the reason that the order looks wrong. 

I then opted to sort by `lastModified`. But it might be a good idea to find out what is happening there.

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by AlexV525** [comment]
Closing with stale state.
