### ISSUE TITLE
[BUG] no response when call getMediaUrl on some video.

### ISSUE THREAD

**Issue by dodatw** [CaiJingLong/flutter_photo_manager#388]
Hi All,

We face an issue on iOS. we have a video picker.
We found we cannot getMediaUrl on some device. (no response)

This issue easy reproduce on iOS "slo-mo" video.

Is there any solution ?

Tommy.

**Comment by AlexV525** [comment]
Is this still reproducible in the latest version (1.2.1)?

**Comment by hannanriaz009** [comment]
Also happened here. Unable to call  getMediaUrl of some videos, when apple account is signed-in in the device.
Every video works fine, if no account is logged in. Tried with latest sdk of Flutter i.e. 2.2.1 and dart 2.13.1. Also, the latest version(1.2.2) of photo manager was used.

**Comment by AlexV525** [comment]
Is this issue occurred on every slow motion videos, or is it related to some iCloud videos?

**Comment by hannanriaz009** [comment]
@AlexV525 
For me it happens on icloud videos. Sometimes I get media url and sometimes I don't. 
I also tried to filter the videos using try catch, but for some cases it does throw exception (comes in catch block) and at times it doesn't.
So its been some days I am totally lost. Now thinking to do something native in IOS to bypass this problem. This has become a deal breaker for me. 
I have tried on latest flutter sdk versions as well. not sure its flutter vs IOS problem or something else.

**Comment by hannanriaz009** [comment]
My requirement is not that tough, all I want is to show all the photos and videos from user's phone (with or without iCloud logged in, synchronised or not synchronise) whatever user is seeing in photos app should appear in my app. And user should be able to play it within the app. 

Any other solution is highly welcomed to achieve the above.

**Comment by hannanriaz009** [comment]
Moreover, I have also tried this library https://pub.dev/packages/photo_gallery and its method to achieve file in order to play video shows same problem (thread dies forever). Which is making me think it's not related to Photo Manager library. It is something Flutter vs IOS... 😞

**Comment by jaysignorello** [comment]
@AlexV525 I'm seeing the same issue on a physical device with SlowMo being the easiest to reproduce.

**Comment by AlexV525** [comment]
Tested with some live photos and this issue seems not reproducible on my device.

Test with:
```dart
Stopwatch watch = Stopwatch()..start();
final String? url = await entity.getMediaUrl();
watch.stop();
print('Media URL: $url');
print(watch.elapsed);
```

Result:
```
flutter: Media URL: null
flutter: 0:00:00.000175
```

**Comment by AlexV525** [comment]
As I investigating, the slow motion video is not an `AVURLAsset` but an `AVComposition` which does not include a property like `AVURLAsset.URL`, makes the slow motion video unable to use the `getMediaUrl` method.

![image](https://user-images.githubusercontent.com/15884415/126269987-14af26a3-e980-407f-8e97-cc2c0b7f78b2.png)

Though there are [some solutions](https://blog.kulman.sk/converting-slow-motion-video-to-url-asset/) to convert an `AVComposition` to `AVURLAsset`, but it requires a storage action during the conversion, which I don't think it's a proper way to handle it.

I still cannot try with iCloud videos, since my device didn't upload any of my videos to iCloud yet and I couldn't find a way to trigger it manually. 😢

**Comment by AlexV525** [comment]
Not sure whether it'll have a side-effect or not, I'll submit a PR to temporary solve it.
