### ISSUE TITLE
[BUG] crash: This application is not allowed to access Photo data.

### ISSUE THREAD

**Issue by Lcccocoa** [CaiJingLong/flutter_photo_manager#480]
ios Crash log:
This application is not allowed to access Photo data.

0 CoreFoundation | ___exceptionPreprocess + 228
1 libobjc.A.dylib | objc_exception_throw + 56
2 PhotoLibraryServices | 0x000000021bdc4000 + 177788
3 Photos | 0x000000021ccdd000 + 809144
4 Photos | 0x000000021ccdd000 + 602268
5 Photos | 0x000000021ccdd000 + 687268
6 AssetsLibraryServices | 0x000000021bae9000 + 38308
7 libdispatch.dylib | __dispatch_client_callout + 16
8 libdispatch.dylib | __dispatch_continuation_pop$VARIANT$mp + 412
9 libdispatch.dylib | __dispatch_source_invoke$VARIANT$mp + 1308
10 libdispatch.dylib | __dispatch_root_queue_drain + 372
11 libdispatch.dylib | __dispatch_worker_thread2 + 128
12 libsystem_pthread.dylib | _pthread_wqthread + 464
13 libsystem_pthread.dylib | start_wqthread + 4

**Comment by CaiJingLong** [comment]
I can't find any info in the log.

**Comment by flywithbug** [comment]
Same bug

*** Terminating app due to uncaught exception 'NSObjectInaccessibleException', reason: 'This application is not allowed to access Photo data.'



1 | CoreFoundation | 0x1f87b5000 | __exceptionPreprocess (in CoreFoundation) + 228
-- | -- | -- | --
2 | libobjc.A.dylib | 0x1f7a9b000 | objc_exception_throw (in libobjc.A.dylib) + 56
3 | PhotoLibraryServices | 0x2065a1000 | -[PLPhotoLibrary initWithTransientContext:name:pathManager:] (in PhotoLibraryServices) + 1320
4 | Photos | 0x20755d000 | -[PHPhotoLibrary photoLibrary] (in Photos) + 108
5 | Photos | 0x20755d000 | -[PHCoreImageManager _performPreheatReferenceCountingOperationForAssets:CPLPrefetching:domain:operation:passingTestHandler:] (in Photos) + 128
6 | Photos | 0x20755d000 | __22-[PHImageManager init]_block_invoke (in Photos) + 344
7 | AssetsLibraryServices | 0x20629a000 | __pl_dispatch_source_set_event_handler_block_invoke (in AssetsLibraryServices) + 36
8 | libdispatch.dylib | 0x1f82a9000 | _dispatch_client_callout (in libdispatch.dylib) + 16
9 | libdispatch.dylib | 0x1f82a9000 | _dispatch_continuation_pop$VARIANT$armv81 (in libdispatch.dylib) + 404
10 | libdispatch.dylib | 0x1f82a9000 | _dispatch_source_invoke$VARIANT$armv81 (in libdispatch.dylib) + 1704
11 | libdispatch.dylib | 0x1f82a9000 | _dispatch_root_queue_drain (in libdispatch.dylib) + 344
12 | libdispatch.dylib | 0x1f82a9000 | _dispatch_worker_thread2 (in libdispatch.dylib) + 116
13 | libsystem_pthread.dylib | 0x1f84e1000 | _pthread_wqthread (in libsystem_pthread.dylib) + 472
14 | libsystem_pthread.dylib | 0x1f84e1000 | start_wqthread (in libsystem_pthread.dylib) + 4

**Comment by AlexV525** [comment]
Please provide version info including package version, system version, and Flutter verison.

**Comment by AlexV525** [comment]
Closing since no further info are provided.
