### ISSUE TITLE
[Help] Store path to image and retrieve.

### ISSUE THREAD

**Issue by momoDragon** [CaiJingLong/flutter_photo_manager#597]
I want to be able to save and retrieve user selection of AssetEntity. So for example user has selected a few that they like, i want to save the selection locally in something like shared preference. And some time in the future, i want to be able to retrieve the AssetEntity again.  How can i achieve that?

**Comment by vishnukvmd** [comment]
You can persist the `id` of the selected `AssetEntity`(s) in your data store (shared preference/SQLite/...) and retrieve the original objects by calling `AssetEntity.fromId(id)`.

**Comment by momoDragon** [comment]
@vishnukvmd  yes i tried that, but seems like the id is a running number, i got like 26 to 29 when I tried it. What will happen if there are more images added to a folder? my concern is that i am not sure what the id is based on, and will it be affected if the files are being changed. 

Also, what does this comment mean?

`  /// Create from [AssetEntity.id], not recommended.
  static Future<AssetEntity?> fromId(String id) async {
    try {
      return await PhotoManager.refreshAssetProperties(id);
    } catch (e) {
      return null;
    }
  }`

**Comment by vishnukvmd** [comment]
You should treat `id` as a string, since on iOS a UUID is what is returned. On Android, it looks like a serial number, so even if new items are added to a folder, you should be able to reference an `AssetEntity` with the original `id` you persisted. 

@CaiJingLong or @AlexV525 will be able to provide more context on the warning.

**Comment by CaiJingLong** [comment]
On IOS, if you use the editing function of the photos app, the id will be retained.

Android is different. Some ROMs in Android delete old resources and create new one. Therefore, the id you keep may not get the correct resources or nothing.

**Comment by AlexV525** [comment]
`AssetEntity.fromId` basically means the plugin will try to obtain the info from your id, which might be failed if the entity for this id is not longer exist, so it's not recommended. But you can still use it to keep your selection or other behaviors related, and be careful when handling retrieve since the result could be nullable.

Closing, based on comments above seem to solved the issue.
