### ISSUE TITLE
UI locks up when requesting iCloud file

### ISSUE THREAD

**Issue by adriancmurray** [CaiJingLong/flutter_photo_manager#71]
If I'm understanding this correctly, the only way to grab a file that's stored on the network (iCloud) is to call fullData on an AssetEntity. I don't see any code that mentions progress (not on the flutter side at least, I do see progress within your ObjectiveC code). The issue is that when I call for fullData on byteArrayLengths that are zero it locks up my UI until the download is complete. Is this really the only solution for grabbing iCloud images?

**Comment by CaiJingLong** [comment]
If you want to get icloud picture completely, the only way is through the API interface provided by apple. This is not a normal network picture, which can not be obtained through http. get. It is a callback of picture information in the block after request.

So the usual practice is to apply for a thumbnail of a small size(100x100/200x200) to fill the UI first, and provide a full-size picture if necessary.
In addition, because the API for accessing pictures is based on PHPhoto, you can use Apple's built-in caching system. After the first visit, the pictures will be accessed again very quickly.

----

There may be other ways to download photos from the Icloud, but I haven't found one, at least not in the PHPhoto library.

----

The download progress is not currently reflected in the flutter.
Because of the 2 point:
1. Android has no api, so it's hard to keep it unified.
2. The download progress is reflected in the flutter side. How to communicate and design the API is a difficult problem. Whether using Future < double > or Stream < double > there may be more unknown errors.

**Comment by adriancmurray** [comment]
I have my own audio player plugin which uses streams to broadcast progress of the currently playing item and that doesn't produce any errors. This is a bidirectional plugin where it's sending and receiving data from the native platform. I don't think there's much of an issue with handing down the data to flutter MethodCall. The alternative is to just use a couple of voidcallbacks to signal that a download started and completed to allow state change. Though, none of this really matters because it's really the call to getting the full bytearray data that's locking up the UI. I was more so curious if the PHPhoto library allowed you to get a File path vs needing to get raw image data. The file should exists somewhere so it seems odd that this full byte data is the only option. I know that I can't use an http request for icloud data, that'd be a security problem on their end and there's no way they'd allow that. I'm just thinking there must be some other way to get a file path vs a full raw image. Either way, thanks for the response.

**Comment by adriancmurray** [comment]
Also, I think the problem with the locking UI is unavoidable unless an isolate was used and that's not currently supported with Flutter's isolate setup. It doesn't allow platform channels to split off of the main isolate. There seems to be a work around for this limitation but I didn't really read beyond that since this isn't a stopper for me, just a minor annoyance that will happen on occasion.

**Comment by CaiJingLong** [comment]
Now, `NSData` or `UIImage` can be provided by PHPhoto in iOS, whether it's an icloud or a local asset.
So, iOS asset has no local file path or url.
The `file` fields you see in this library are generated only when you get the file.

**Comment by adriancmurray** [comment]
I completely missed that when I looked through the Objective C code. Thank you for the information.
