### ISSUE TITLE
Check for new images that where not cached previously

### ISSUE THREAD

**Issue by Shtibel** [CaiJingLong/flutter_photo_manager#80]
## Expect
What I am trying to do is this:
1. First time opening the application:
    - Show loader until we get all the images
    - Save in device shared preferences that we have cached images
2. next time opening the application:
    - Check on device shared preferences that we have cached images
    - Get all the images from cache
    - Check if there are new images that were not cached previously
    - If there are new images, cache the new images

How can I do this?
Can you show an example ?

**Comment by CaiJingLong** [comment]
I'm sorry to reply so long. Maybe you no longer use this library, but I still want to add a reply so that other users can see it later.

---

1. You need to create your own cache mechanism, such as using a database or a key-value database,
2. Use id as the primary key and your own cache picture uri (filePath) as the value
3. Before reading, check the asset's database. If there is an id, read your own local cache file. If not, get it from photo_manager. After successful acquisition, cache it to your database

But I don't recommend doing this, my suggestion is to directly use FutureBuilder with photo_manager's api to load images and display or handle file data.
